### ISSUE TITLE
This is really awesome list, but how can we verify the lab/project results?

### ISSUE THREAD

**Issue by pangjac** [PKUFlyingPig/Self-learning-Computer-Science#2]
Hi PKUFP,
Thanks for sharing this list. It is really awesome and listed with an reasonable order to learn.
A key confusion is, when self-learning. how do you verify the homework/lab/project results ?   I noticed you mentioned for `61B` there is a gradescipe code to autograde, which is really helpful.
 However, for other courses, what is your advice to verify lab/projects if you ( we ) have implemented them correctly?

Thanks! and Best wishes to you! # # # #

**Comment by PKUFlyingPig** [comment]
Sorry for the delayed reply  ~ I think your question is not a real problem. Almost all of the courses I took which have some kind of coding labs will have testing codes accompanied with its start code. And even the writing homework ( some maths courses may not have coding hw) will have the solution version. I believe I have saved all of them in my repository which you can redirect into following the links in the README. Hope this can answer your questions.
