### ISSUE TITLE
vscode和sublime都不是ide吧

### ISSUE THREAD

**Issue by xtst** [PKUFlyingPig/Self-learning-Computer-Science#3]
[源链接
](https://pkuflyingpig.github.io/pku-cs-self-learning/CS%E5%AD%A6%E4%B9%A0%E8%A7%84%E5%88%92/)

> IDE（Integrated Development Environment）：集成开发环境，说白了就是你写代码的地方。作为一个码农，IDE的重要性不言而喻，一个轻便的编辑器可以让你从产生一个编程点子到开始写代码之间只隔了一个快捷键。个人推荐常用的IDE是VSCode和Sublime（准确的说Sublime只是一个编辑器，但丰富的插件使它基本满足了我的轻量级编程需求）。当然对于大型项目我还是会采用略重型的IDE，例如Pycharm（Python），IDEA（Java）等等（免责申明：所有的IDE都是世界上最好的IDE）。

---
vscode和sublime都是编辑器吧，都不是IDE。

我就是大一新生，不过不是你北的。我觉得编辑器并不太适合没基础的新生，配置比较繁琐，花半天一天甚至好几天配置不好环境的新生比比皆是（写前端之类的另说，不过新生写前端的少吧）

比如学C++，私以为dev-cpp、codeblocks、visual studio都比vscode、sublime更适合小白直接上手，clion虽然是ide不过还是要自己设置编译器路径，所以也是有门槛。

**Comment by PKUFlyingPig** [comment]
嗯嗯vscode确实不是严格意义上的IDE，已经修改了这个笔误。

但对于编辑器不适合新手这个观点我不太赞同，我觉得vscode基本不需要太多配置。反倒是visual studio这种IDE我感觉过于重型，新生就写个单文件的C程序也要建个工程繁琐不说也不能体验到程序编译执行的流程。

当然这个体验应该是因人而异的，我把IDE和编辑器都列出来了供大家选择。

**Comment by fuhailin** [comment]
我赞同不使用IDE进行编程学习，ide集成了所有编译、链接、智能提示等功能，使得初学者无法了解到程序从代码到可执行程序的过程

**Comment by PKUFlyingPig** [comment]
观点因人而异，这个issue暂时不涉及项目内容修改的问题了，所以我closed掉了。
